version: 0.0
os: linux
files:
  - source: /
    destination: /Political-Journal
permissions:
  - object: /Political-Journal
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 300
      runas: root
